eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
server:
  port: 8804 #feign的端口
spring:
  application:
    name: feign-consumer  #服务的名称id
feign:
  hystrix:
    enabled: true
